// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"database/sql"
)

type Author struct {
	ID   int32  `json:"id"`
	Name string `json:"name"`
}

type Task struct {
	ID          int32          `json:"id"`
	Title       string         `json:"title"`
	Description sql.NullString `json:"description"`
	Status      string         `json:"status"`
}

type TaskAuthor struct {
	TaskID   int32 `json:"task_id"`
	AuthorID int32 `json:"author_id"`
}
